<?php

namespace AppBundle\Repository;

/**
 * KpLocalCallsDailyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KpLocalCallsDailyRepository extends \Doctrine\ORM\EntityRepository
{
    public function getStateDaily($state, $type, $year, $month)
    {
        $qb = $this->createQueryBuilder('r');
        $query = $qb->select(
            "r.dayNum as day, SUM(r.callsLocals) as total_count, r.month as month"
        )
            ->where("r.month = :month")
            ->andWhere("r.year = :year")
            //->andWhere('r.state = :state')
            ->groupBy('r.dayNum')
            ->orderBy('r.dayNum')
            ->setParameter('month', $month)
            ->setParameter('year', $year)
            //->setParameter('state', $state)
        ;
        $restresult = $query->getQuery()->getResult();
        return $restresult;
    }
}
