imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@AppBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Assetic Config
assetic:
    debug: '%kernel.debug%'
    use_controller: false
    bundles: []
    filters:
      cssrewrite: ~

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.project_dir%/var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        entity_managers:
            default:
                auto_mapping: true
                dql:
                    datetime_functions:
                        date: DoctrineExtensions\Query\Mysql\Date
                        date_format: DoctrineExtensions\Query\Mysql\DateFormat
                        dateadd: DoctrineExtensions\Query\Mysql\DateAdd
                        datediff: DoctrineExtensions\Query\Mysql\DateDiff
                        day: DoctrineExtensions\Query\Mysql\Day
                        dayname: DoctrineExtensions\Query\Mysql\DayName
                        last_day: DoctrineExtensions\Query\Mysql\LastDay
                        minute: DoctrineExtensions\Query\Mysql\Minute
                        second: DoctrineExtensions\Query\Mysql\Second
                        strtodate: DoctrineExtensions\Query\Mysql\StrToDate
                        str_to_date: DoctrineExtensions\Query\Mysql\StrToDate
                        time: DoctrineExtensions\Query\Mysql\Time
                        timestampadd: DoctrineExtensions\Query\Mysql\TimestampAdd
                        timestampdiff: DoctrineExtensions\Query\Mysql\TimestampDiff
                        week: DoctrineExtensions\Query\Mysql\Week
                        weekday: DoctrineExtensions\Query\Mysql\WeekDay
                        year: DoctrineExtensions\Query\Mysql\Year

                    numeric_functions:
                        acos: DoctrineExtensions\Query\Mysql\Acos
                        asin: DoctrineExtensions\Query\Mysql\Asin
                        atan2: DoctrineExtensions\Query\Mysql\Atan2
                        atan: DoctrineExtensions\Query\Mysql\Atan
                        cos: DoctrineExtensions\Query\Mysql\Cos
                        cot: DoctrineExtensions\Query\Mysql\Cot
                        hour: DoctrineExtensions\Query\Mysql\Hour
                        pi: DoctrineExtensions\Query\Mysql\Pi
                        power: DoctrineExtensions\Query\Mysql\Power
                        quarter: DoctrineExtensions\Query\Mysql\Quarter
                        rand: DoctrineExtensions\Query\Mysql\Rand
                        round: DoctrineExtensions\Query\Mysql\Round
                        sin: DoctrineExtensions\Query\Mysql\Sin
                        std: DoctrineExtensions\Query\Mysql\Std
                        tan: DoctrineExtensions\Query\Mysql\Tan

                    string_functions:
                        binary: DoctrineExtensions\Query\Mysql\Binary
                        char_length: DoctrineExtensions\Query\Mysql\CharLength
                        concat_ws: DoctrineExtensions\Query\Mysql\ConcatWs
                        countif: DoctrineExtensions\Query\Mysql\CountIf
                        crc32: DoctrineExtensions\Query\Mysql\Crc32
                        degrees: DoctrineExtensions\Query\Mysql\Degrees
                        field: DoctrineExtensions\Query\Mysql\Field
                        find_in_set: DoctrineExtensions\Query\Mysql\FindInSet
                        group_concat: DoctrineExtensions\Query\Mysql\GroupConcat
                        ifelse: DoctrineExtensions\Query\Mysql\IfElse
                        ifnull: DoctrineExtensions\Query\Mysql\IfNull
                        match_against: DoctrineExtensions\Query\Mysql\MatchAgainst
                        md5: DoctrineExtensions\Query\Mysql\Md5
                        month: DoctrineExtensions\Query\Mysql\Month
                        monthname: DoctrineExtensions\Query\Mysql\MonthName
                        nullif: DoctrineExtensions\Query\Mysql\NullIf
                        radians: DoctrineExtensions\Query\Mysql\Radians
                        regexp: DoctrineExtensions\Query\Mysql\Regexp
                        replace: DoctrineExtensions\Query\Mysql\Replace
                        sha1: DoctrineExtensions\Query\Mysql\Sha1
                        sha2: DoctrineExtensions\Query\Mysql\Sha2
                        soundex: DoctrineExtensions\Query\Mysql\Soundex
                        uuid_short: DoctrineExtensions\Query\Mysql\UuidShort

sensio_framework_extra:
    view: { annotations: true }

nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: []
        allow_headers: []
        allow_methods: []
        expose_headers: []
        max_age: 0
        hosts: []
    paths:
        '^/':
            allow_origin: ['*']
            allow_headers: ['X-Requested-With', 'Content-Type', 'authorization', 'Access-Control-Request-Headers']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS', 'PATCH']
            max_age: 3600

fos_rest:
    disable_csrf_role: ROLE_API
    param_fetcher_listener: true
    routing_loader:
        default_format:       ~
        include_format:       false
    view:
        mime_types:
            json: ['application/json; charset=utf-8', 'application/json', 'application/json;version=1.0', 'application/json;version=1.1', 'application/xml']
        view_response_listener: 'force'
        formats:
            xml:  true
            json: true
        templating_formats:
            html: true
    format_listener:
        rules:
            - { path: ^/, priorities: [ json, html, xml ], fallback_format: ~, prefer_extension: false }

    exception:
        codes:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
            'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
        messages:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': true
    allowed_methods_listener: true
    access_denied_listener:
        json: true
    body_listener: true

knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }